name: Scheduled Tests

on:
   schedule: 
     - cron: '15 7 * * *' # Runs the workflow every day at 12:13 PM PKT (07:13 UTC)

jobs:
  automated-tests:
    runs-on: windows-latest
    steps:
      - run: npm node --version
